### ISSUE TITLE
YAML output: CSL Items are written with non-standard YAML tags

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#280]
From `manubot cite --yml arxiv:1710.05980`:

```yaml
- !!python/object/new:manubot.cite.arxiv.CSL_Item_arXiv
  dictitems:
    id: aLsdEzlV
    URL: https://arxiv.org/abs/1710.05980
    number: '1710.05980'
    title: 'SMR: Medical Knowledge Graph Embedding for Safe Medicine Recommendation'
    issued:
      date-parts:
      - - 2020
        - 12
        - 1
    author:
    - given: Fang
      family: Gong
    - given: Meng
      family: Wang
    - given: Haofen
      family: Wang
    - given: Sen
      family: Wang
    - given: Mengyue
      family: Liu
    container-title: arXiv
    publisher: arXiv
    type: report
    note: |-
      license: http://arxiv.org/licenses/nonexclusive-distrib/1.0/
      This CSL Item was generated by Manubot v0.5.0 from its persistent identifier (standard_id).
      standard_id: arxiv:1710.05980
```
