### ISSUE TITLE
Support updated GitHub repository citations

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#296]
GitHub announced support for better repository citation via a CITATION.cff file, and Zotero [announced](https://twitter.com/zotero/status/1420515377390530560) a [translator ](https://github.com/zotero/translators/blob/master/GitHub.js) to make use of that information.

Would we like to test how these updated repository citations work with Manubot?  I believe we would need to update `translate.manubot.org` as described in https://github.com/manubot/manubot/issues/216#issuecomment-625356574.

**Comment by dhimmel** [comment]
Okay I'll update the translation server. Here's the before output of `manubot cite https://github.com/citation-file-format/ruby-cff`:

```json
[
  {
    "id": "dYvFAcWw",
    "type": "webpage",
    "title": "GitHub - citation-file-format/ruby-cff: A Ruby library for manipulating CITATION.cff files.",
    "container-title": "GitHub",
    "abstract": "A Ruby library for manipulating CITATION.cff files. - GitHub - citation-file-format/ruby-cff: A Ruby library for manipulating CITATION.cff files.",
    "URL": "https://github.com/citation-file-format/ruby-cff",
    "shortTitle": "GitHub - citation-file-format/ruby-cff",
    "language": "en",
    "accessed": {
      "date-parts": [
        [
          "2021",
          8,
          20
        ]
      ]
    },
    "note": "This CSL Item was generated by Manubot v0.5.0 from its persistent identifier (standard_id).\nstandard_id: url:https://github.com/citation-file-format/ruby-cff"
  }
]
```

**Comment by dhimmel** [comment]
In the process of updating.  `git pull --ff-only --recurse-submodules` had the following effect:

```
Submodule path 'modules/translators': checked out '6bfdb8f4eadc4d28ae3b2eebc5c25e4e023645be'
```

Ran into an issue related to https://github.com/npm/cli/issues/2610#issuecomment-900031204 / https://github.com/zotero/translation-server/commit/cd1b01cb93aca5b17f8372219172d73c90ad067d where I can't do `npm install` because it tries to use SSH key authentication which is not configured.

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/zotero/wicked-good-xpath.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

**Comment by dhimmel** [comment]
As a workaround, I created an SSH key on the translation-server instance at `/home/translate/.ssh/id_ed25519` and then added this a read-only deploy key at https://github.com/manubot/manubot/settings/keys:

![image](https://user-images.githubusercontent.com/1117703/130323077-44d6dfcf-2046-4aeb-8539-a058c4fac3dc.png)

We can delete this later if the npm issue is resolved.

**Comment by dhimmel** [comment]
Looks like the [GitHub translator in the translator submodule](https://github.com/zotero/translators/blob/6bfdb8f4eadc4d28ae3b2eebc5c25e4e023645be/GitHub.js) hasn't been updated yet. So we'll need to wait for the translation-server repo to update the `translator` submodule. CC @dstillman

**Comment by dstillman** [comment]
I've updated the submodule, but note that translators are updated [all the time](https://github.com/zotero/translators/commits/master), and I'd recommend adding a mechanism to automatically update local translators (e.g., hard-resetting translators to the latest remote commit and restarting the server once a day). We've talked about building automatic updates into the server but that doesn't exist at the moment.

**Comment by agitter** [comment]
This was closed by https://github.com/manubot/manubot/issues/82#issuecomment-1308061544 and the related Zotero translation server updates. We can now cite GitHub repositories and use the metadata in the cff file.

```
$ manubot cite https://github.com/citation-file-format/ruby-cff
[
  {
    "id": "dYvFAcWw",
    "type": "book",
    "abstract": "A Ruby library for manipulating CITATION.cff files.",
    "genre": "Ruby",
    "note": "DOI: 10.5281/zenodo.1184077\nThis CSL Item was generated by Manubot v0.5.3 from its persistent identifier (standard_id).\nstandard_id: url:https://github.com/citation-file-format/ruby-cff",
    "source": "GitHub",
    "title": "Ruby CFF Library",
    "URL": "https://github.com/citation-file-format/ruby-cff",
    "author": [
      {
        "family": "Haines",
        "given": "Robert"
      },
      {
        "family": "The Ruby Citation File Format Developers",
        "given": ""
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2022",
          11,
          24
        ]
      ]
    },
    "issued": {
      "date-parts": [
        [
          "2022",
          11
        ]
      ]
    }
  }
]
```

I'm not sure that `"type": "book"` is the best choice and date issued drops the day, but we're deferring to Zotero here.  It's an improvement over the old GitHub metadata shown above.  For reference, the relevant parts of the [cff file](https://github.com/citation-file-format/ruby-cff/blob/4acdc80ff823fad0f8a3ee0c8a6a8160750a3fbe/CITATION.cff):
```
title: Ruby CFF Library
abstract: This library provides a Ruby interface to manipulate Citation File Format files
authors:
- family-names: Haines
  given-names: Robert
  orcid: https://orcid.org/0000-0002-9538-7919
  affiliation: The University of Manchester, UK
- name: The Ruby Citation File Format Developers
keywords:
- ruby
- credit
- software citation
- research software
- software sustainability
- metadata
- citation file format
- CFF
version: 1.0.1
doi: 10.5281/zenodo.1184077
date-released: 2022-11-05
license: Apache-2.0
repository-artifact: https://rubygems.org/gems/cff
repository-code: https://github.com/citation-file-format/ruby-cff
```
I'm ignoring the `cff-version`, `message`, and `references`.
